spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: false
    name: blog
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
